FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/HelloOrder.Api/HelloOrder.Api.csproj", "HelloOrder.Api/"]
COPY ["src/HelloOrder.Application/HelloOrder.Application.csproj", "HelloOrder.Application/"]
COPY ["src/HelloOrder.Infrastructure/HelloOrder.Infrastructure.csproj", "HelloOrder.Infrastructure/"]
COPY ["src/HelloOrder.Core/HelloOrder.Core.csproj", "HelloOrder.Core/"]
RUN dotnet restore "HelloOrder.Api/HelloOrder.Api.csproj"
COPY src/ .
WORKDIR "/src/HelloOrder.Api"
RUN dotnet build "HelloOrder.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HelloOrder.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HelloOrder.Api.dll"]
